# Generated by Django 3.1.2 on 2020-12-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(blank=True, default=1, null=True, verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('background', models.ImageField(blank=True, null=True, upload_to='productos/images', verbose_name='Fondo')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('vertical', models.IntegerField(max_length=100, verbose_name='Medida Vertical')),
                ('horizontal', models.IntegerField(max_length=100, verbose_name='Medida Horizontal')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('unit', models.CharField(max_length=10, verbose_name='Unidad')),
            ],
        ),
        migrations.DeleteModel(
            name='Backgroung',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mano de Obra'),
        ),
        migrations.AddField(
            model_name='size',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.typesize'),
        ),
        migrations.AddField(
            model_name='pricer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product'),
        ),
        migrations.AddField(
            model_name='pricer',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.season'),
        ),
        migrations.AddField(
            model_name='pricer',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.size'),
        ),
    ]
