# Generated by Django 3.1.2 on 2020-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20201201_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ram', models.IntegerField(blank=True, default=1, null=True, verbose_name='Memoria RAM')),
                ('storage', models.CharField(max_length=100, verbose_name='Almacenamiento')),
                ('storage_aux', models.CharField(max_length=100, verbose_name='Almacenamiento Secundario')),
                ('screen', models.CharField(max_length=100, verbose_name='Pantalla')),
                ('system', models.CharField(max_length=100, verbose_name='S.O')),
                ('bonus', models.CharField(max_length=250, verbose_name='Adicionales')),
                ('normal_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Normal')),
                ('ofert_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Oferta')),
            ],
        ),
        migrations.AddField(
            model_name='size',
            name='description',
            field=models.IntegerField(default=12, max_length=100, verbose_name='Tam. Descripcion'),
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.IntegerField(default=12, max_length=100, verbose_name='Tam. Precio'),
        ),
        migrations.AddField(
            model_name='size',
            name='title',
            field=models.IntegerField(default=24, max_length=100, verbose_name='Tam. Titulo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
        ),
    ]
