# Generated by Django 3.1.2 on 2020-12-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20201201_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerPricer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(blank=True, default=1, null=True, verbose_name='Cantidad')),
                ('Computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.computer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.season')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.size')),
            ],
        ),
    ]
