# Generated by Django 3.1.2 on 2020-12-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20201206_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='bonus',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adicionales'),
        ),
    ]
