# Generated by Django 3.1.2 on 2020-12-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20201215_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(default=0, max_length=50, verbose_name='UPC'),
        ),
    ]
