# Generated by Django 3.1.2 on 2020-12-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_product_upc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Existencia'),
        ),
    ]
