# Generated by Django 3.1.2 on 2020-12-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_normal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Normal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Oferta'),
        ),
    ]
