# Generated by Django 3.1.2 on 2020-12-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20201217_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='upc',
            field=models.CharField(default=0, max_length=50, verbose_name='UPC'),
        ),
    ]
