# Generated by Django 3.1.2 on 2020-12-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_computer_upc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='bonus',
            new_name='other',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='storage_aux',
        ),
        migrations.AddField(
            model_name='computer',
            name='hdd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='HDD'),
        ),
        migrations.AddField(
            model_name='computer',
            name='hz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Frecuenta de pantalla'),
        ),
        migrations.AddField(
            model_name='computer',
            name='ssd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SSD'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='S.O'),
        ),
    ]
